version: 2.1

parameters:
  python-version:
    type: string
    default: "3.9"

executors:
  python_executor:
    machine:
      image: ubuntu-2204:current  # Máquina Linux compatible

jobs:
  setup:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: Crear y activar entorno virtual
          command: |
            python3 -m venv venv
            source venv/bin/activate
      - run:
          name: Instalar dependencias
          command: |
            source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt
      - run:
          name: Verificar Python y Django
          command: |
            source venv/bin/activate && python --version && python -m django --version

  migrate:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: Depurar entorno virtual
          command: |
            source venv/bin/activate && which python  # Verificar que apunta a 'venv'
      - run:
          name: Verificar dependencias instaladas
          command: |
            source venv/bin/activate && pip freeze  # Verificar si todo está instalado
      - run:
          name: Aplicar migraciones
          command: |
            source venv/bin/activate && python manage.py migrate

  notify_success:
    executor: python_executor
    steps:
      - run:
          name: Notificación de éxito en Slack
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Pipeline completado exitosamente :white_check_mark:"}' $SLACK_WEBHOOK_URL

workflows:
  version: 2

  setup_workflow:
    jobs:
      - setup

  migration_workflow:
    jobs:
      - setup
      - migrate:
          requires:
            - setup
      - notify_success:
          requires:
            - migrate
