version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12.5  # Imagen next-gen de Python 3.12.5
    working_directory: ~/repo

jobs:
  # Job 1: Install Dependencies
  install_dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias con pip (sin virtualenv)
          command: |
            pip install -r requirements.txt

  # Job 2: Linter Check
  lint_code:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Verificar el estilo del código con flake8
          command: |
            pip install flake8
            flake8 .

  # Job 3: Clonar un Repositorio Público
  clone_repo:
    executor: python-executor
    steps:
      - run:
          name: Clonar repositorio público
          command: |
            git clone https://github.com/python/cpython.git ~/repo/cpython
            echo "Repositorio clonado correctamente."

  # Job 4: Simulación de Despliegue
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Simulación de despliegue
          command: |
            echo "Iniciando despliegue..."
            # Aquí se puede integrar con un servicio de despliegue real.
            echo "Despliegue finalizado."

workflows:
  # Workflow 1: Verify and Prepare
  verify_and_prepare:
    jobs:
      - install_dependencies
      - lint_code:
          requires:
            - install_dependencies

  # Workflow 2: Clone and Deploy
  clone_and_deploy:
    jobs:
      - clone_repo
      - deploy:
          requires:
            - clone_repo
