version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  # Job 1: Crear y activar entorno virtual + instalar dependencias
  install_dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Crear entorno virtual
          command: |
            python3 -m venv venv
            ls -l  # Verifica que la carpeta venv se haya creado
      - run:
          name: Activar entorno virtual y verificar Python
          command: |
            if [ -f "venv/bin/activate" ]; then
              source venv/bin/activate
              which python || { echo "Error: No se pudo activar el entorno virtual"; exit 1; }
            else
              echo "Error: El entorno virtual no existe"; exit 1;
            fi
      - run:
          name: Instalar dependencias
          command: |
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

  # Job 2: Revisar estilo de código con Flake8
  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Activar entorno virtual y ejecutar Flake8
          command: |
            source venv/bin/activate
            pip install flake8
            flake8 .

  # Job 3: Análisis estático del código con Bandit
  code_quality:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Activar entorno virtual y ejecutar Bandit
          command: |
            source venv/bin/activate
            pip install bandit
            bandit -r .  # Analiza recursivamente la seguridad del código

  # Job 4: Notificación a Slack
  notify_slack:
    executor: python-executor
    steps:
      - run:
          name: Enviar notificación a Slack
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Pipeline terminado correctamente en CircleCI :white_check_mark:"}' \
            $SLACK_WEBHOOK_URL

workflows:
  # Workflow Unificado: Validación y Notificación
  validate_and_notify:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - code_quality:
          requires:
            - install_dependencies
      - notify_slack:
          requires:
            - lint
            - code_quality
