version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12.5  # Imagen next-gen de Python recomendada por CircleCI
    working_directory: ~/repo

jobs:
  # Job 1: Install Dependencies
  install_dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Instalar dependencias con pip (sin virtualenv)
          command: |
            pip install -r requirements.txt

  # Job 2: Linter Check
  lint_code:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Verificar el estilo del código con flake8
          command: |
            pip install flake8
            flake8 .

  # Job 3: Static Files Collection
  collect_static:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Ejecutar collectstatic
          command: |
            python manage.py collectstatic --no-input

  # Job 4: Deployment Simulated
  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Simulación de despliegue
          command: |
            echo "Iniciando despliegue..."
            # Aquí se puede integrar con un servicio de despliegue real, si es necesario.
            echo "Despliegue finalizado."

workflows:
  # Workflow 1: Verify and Prepare
  verify_and_prepare:
    jobs:
      - install_dependencies
      - lint_code:
          requires:
            - install_dependencies

  # Workflow 2: Collect Static and Deploy
  static_and_deploy:
    jobs:
      - collect_static
      - deploy:
          requires:
            - collect_static
