version: 2.1

orbs:
  slack: circleci/slack@4.7.0  # Orb de Slack para notificaciones

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9  # Imagen base de Python
    resource_class: medium
    environment:
      DJANGO_SETTINGS_MODULE: my_project.settings
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/mydb

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout  # Clona el repo
      - run:
          name: Instalar dependencias
          command: pip install -r requirements.txt

  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Lint con flake8
          command: flake8 my_project/
      - slack/notify:
          channel: "#ci-notifications"
          event: fail
          template: basic_fail_1

  check-migrations:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Verificar migraciones pendientes
          command: python manage.py makemigrations --check --dry-run
      - slack/notify:
          channel: "#ci-notifications"
          event: fail
          template: basic_fail_1

  static-analysis:
    executor: python-executor
    parallelism: 4  # Ejecución en paralelo
    steps:
      - checkout
      - run:
          name: Análisis estático con Bandit
          command: bandit -r my_project/
      - slack/notify:
          channel: "#ci-notifications"
          event: fail
          template: basic_fail_1

workflows:
  build:
    jobs:
      - install-dependencies
      - check-migrations

  lint-and-analysis:
    jobs:
      - lint
      - static-analysis
