version: 2.1

parameters:
  python-version:
    type: string
    default: "3.9"

executors:
  python_executor:
    machine:
      image: ubuntu-2204:current  # Máquina Linux estándar

jobs:
  setup:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: Verificar Python 3 disponible
          command: python3 --version  # Asegúrate de que Python 3 esté instalado
      - run:
          name: Crear entorno virtual
          command: |
            python3 -m venv venv || { echo "Error: No se pudo crear el entorno virtual"; exit 1; }
      - run:
          name: Verificar entorno virtual creado
          command: |
            if [ ! -d "venv" ]; then echo "Error: Entorno virtual no existe"; exit 1; fi
      - run:
          name: Activar entorno virtual e instalar dependencias
          command: |
            source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt
      - run:
          name: Verificar versiones de Python y Django
          command: |
            source venv/bin/activate && python --version && python -m django --version

  migrate:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: Verificar que Python apunte al entorno virtual
          command: |
            source venv/bin/activate && which python || { echo "Error: No se pudo activar el entorno virtual"; exit 1; }
      - run:
          name: Aplicar migraciones
          command: |
            source venv/bin/activate && python manage.py migrate || { echo "Error: Migraciones fallidas"; exit 1; }

  notify_success:
    executor: python_executor
    steps:
      - run:
          name: Enviar notificación de éxito a Slack
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Pipeline completado exitosamente :white_check_mark:"}' $SLACK_WEBHOOK_URL

workflows:
  version: 2

  setup_workflow:
    jobs:
      - setup

  migration_workflow:
    jobs:
      - setup
      - migrate:
          requires:
            - setup
      - notify_success:
          requires:
            - migrate
