version: 2.1

parameters:
  python-version:
    type: string
    default: "3.9"

jobs:
  setup:
    machine:
      image: windows-server-2019  # Usa Windows como sistema base
    steps:
      - checkout
      - run:
          name: Crear y activar entorno virtual
          command: |
            python -m venv venv
            .\venv\Scripts\activate
      - run:
          name: Instalar dependencias
          command: |
            .\venv\Scripts\activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Verificar versiones de Python y Django
          command: |
            python --version
            python -m django --version

  lint:
    machine:
      image: windows-server-2019
    parallelism: 2  # Ejecuta en paralelo
    steps:
      - checkout
      - run:
          name: Activar entorno virtual e instalar linters
          command: |
            .\venv\Scripts\activate
            pip install flake8
      - run:
          name: Analizar código con Flake8
          command: |
            .\venv\Scripts\activate
            flake8 . --count --max-line-length=88 --statistics

  migrate:
    machine:
      image: windows-server-2019
    steps:
      - checkout
      - run:
          name: Activar entorno virtual y aplicar migraciones
          command: |
            .\venv\Scripts\activate
            python manage.py migrate

  check_dependencies:
    machine:
      image: windows-server-2019
    steps:
      - checkout
      - run:
          name: Activar entorno virtual e instalar herramientas
          command: |
            .\venv\Scripts\activate
            pip install safety
      - run:
          name: Verificar vulnerabilidades en dependencias
          command: |
            .\venv\Scripts\activate
            safety check --full-report

  notify:
    machine:
      image: windows-server-2019
    steps:
      - run:
          name: Enviar notificación a Slack
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Pipeline completado exitosamente en CircleCI :white_check_mark:"}' $SLACK_WEBHOOK_URL

workflows:
  version: 2

  setup_workflow:
    jobs:
      - setup
      - lint:
          requires:
            - setup

  analysis_workflow:
    jobs:
      - setup  # Ejecutar setup nuevamente en este workflow
      - migrate:
          requires:
            - setup
      - check_dependencies:
          requires:
            - migrate
      - notify:
          requires:
            - check_dependencies
