version: 2.1

orbs:
  slack: circleci/slack@4.9.2  # Orb para notificaciones de Slack

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9  # Imagen base para el entorno
    resource_class: medium
    environment:
      DJANGO_SETTINGS_MODULE: my_project.settings
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/mydb

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout  # Clona el repo
      - run:
          name: Instalar dependencias
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  lint:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Lint con flake8
          command: |
            . venv/bin/activate
            flake8 my_project/
      - slack/notify:
          event: fail
          template: basic_fail_1

  check-migrations:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Comprobar migraciones pendientes
          command: |
            . venv/bin/activate
            python manage.py makemigrations --check --dry-run
      - slack/notify:
          event: fail
          template: basic_fail_1

  static-analysis:
    executor: python-executor
    parallelism: 4  # Aquí aplicamos paralelismo
    steps:
      - checkout
      - run:
          name: Análisis estático con Bandit
          command: |
            . venv/bin/activate
            bandit -r my_project/
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  build:
    jobs:
      - install-dependencies
      - check-migrations

  lint-and-analysis:
    jobs:
      - lint
      - static-analysis
